#!/bin/bash
set -e

CMD_TEMPLATE="$*"
interpolateCmd(){
	echo "$CMD_TEMPLATE" | sed "s!%!$1!g"
}

# for every line of stdin
while read -r input|| [ -n "$input" ]; do
	# replace % in the $* with the line
	cmd="$(interpolateCmd $input)"
	# run the resulting command

	# trying to preserve trailing \n, but giving up for now
	outputs="$(eval $cmd | sed 's/\\n/\
/g' ; printf x)"
	outputs="${outputs%x}"

	# for every line of the resulting command
	while read -r output || [ -n "$output" ]; do
		prefix=""
		if [ -z "$XARSPAND_PREFIX" ] ; then
			# output the line, and a XARSPAND_IFS separator (or space)
			prefix="$input${XARSPAND_IFS:- }"
		fi
		# output
		echo "$prefix$output${XARSPAND_POSTFIX:-}"
	done <<< "$outputs"
done
